name: PR Quality Assurance

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  check_labels:
    name: Ensure labels are present
    runs-on: ubuntu-latest
    steps:
      - uses: docker://agilepathway/pull-request-label-checker:latest
        with:
          any_of: enhancement,bug,documentation,refactor,performance,maintenance,dependabot,security,release
          repo_token: ${{ secrets.GITHUB_TOKEN }}
